### PR TITLE
fix code instability of axes

### LINKED ISSUE #116: Type instability in axes(arr,dim)
The method returns an `IdOffsetRange` or a `Base.OneTo` depending on whether the value of `dim` is less than `ndims(arr)`. For example:

```julia
julia> a = OffsetVector(rand(3),-1:1);

julia> @code_warntype axes(a,1)
Variables
  #self#::Core.Compiler.Const(axes, false)
  A::OffsetArray{Float64,1,Array{Float64,1}}
  d::Int64

Body::Union{Base.OneTo{Int64}, OffsetArrays.IdOffsetRange{Int64,Base.OneTo{Int64}}}
1 ─       nothing
│   %2  = OffsetArrays.ndims(A)::Core.Compiler.Const(1, false)
│   %3  = (d <= %2)::Bool
└──       goto #3 if not %3
2 ─ %5  = OffsetArrays.parent(A)::Array{Float64,1}
│   %6  = OffsetArrays.axes(%5, d)::Base.OneTo{Int64}
│   %7  = Base.getproperty(A, :offsets)::Tuple{Int64}
│   %8  = Base.getindex(%7, d)::Int64
│   %9  = OffsetArrays.IdOffsetRange(%6, %8)::OffsetArrays.IdOffsetRange{Int64,Base.OneTo{Int64}}
└──       return %9
3 ─ %11 = Base.OneTo::Core.Compiler.Const(Base.OneTo, false)
│   %12 = (%11)(1)::Core.Compiler.Const(Base.OneTo(1), false)
└──       return %12
```

Perhaps this might return an `IdOffsetRange` in each case?

### PR DESCRIPTION
**Pull request by johnnychen94**
This fixes #116

Switching from `Base.OneTo` to `IdOffsetRange` might introduces some incompatibility issue for downstream packages since IIUC `IdOffsetRange` is still at experimental status, so I'd prefer to not merge this PR until we revisit and polish the design of `IdOffsetRange`.

P.S., perhaps surprisingly, the type instability in #116 doesn't slow down the codes:

```julia
julia> @btime axes(a)
  17.472 ns (1 allocation: 32 bytes)
(-1:1,)

julia> @btime axes(a, 1)
  18.725 ns (1 allocation: 32 bytes)
-1:1

julia> @btime axes(a, 2)
  17.037 ns (0 allocations: 0 bytes)
Base.OneTo(1)
```

cc: @jishnub

### CODE REVIEW

**Comment by goretkin** [comment]
I don't think this will be an issue in practice, but worth noting that

```julia
julia> @code_llvm first(Base.OneTo(3))

;  @ range.jl:566 within `first'
define i64 @julia_first_19563([1 x i64] addrspace(11)* nocapture nonnull readonly dereferenceable(8)) {
top:
  ret i64 1
}
```

but

```julia
julia> @code_llvm first(OffsetArrays.IdOffsetRange(Base.OneTo(3)))

;  @ /Users/goretkin/.julia/dev/OffsetArrays/src/axes.jl:150 within `first'
define i64 @julia_first_19558({ [1 x i64], i64 } addrspace(11)* nocapture nonnull readonly dereferenceable(16)) {
top:
; ┌ @ Base.jl:33 within `getproperty'
   %1 = getelementptr inbounds { [1 x i64], i64 }, { [1 x i64], i64 } addrspace(11)* %0, i64 0, i32 1
; └
; ┌ @ int.jl:53 within `+'
   %2 = load i64, i64 addrspace(11)* %1, align 8
   %3 = add i64 %2, 1
; └
  ret i64 %3
}
```


The reason I think the type instability here is fine is due to constant propagation, is my guess.

File: src/OffsetArrays.jl [hunk 1]
```diff
@@ -92,8 +92,8 @@ Base.eachindex(::IndexLinear, A::OffsetVector)   = axes(A, 1)
 @inline Base.size(A::OffsetArray, d) = size(parent(A), d)
 
 @inline Base.axes(A::OffsetArray) = map(IdOffsetRange, axes(parent(A)), A.offsets)
-@inline Base.axes(A::OffsetArray, d) = d <= ndims(A) ? IdOffsetRange(axes(parent(A), d), A.offsets[d]) : Base.OneTo(1)
-@inline Base.axes1(A::OffsetArray{T,0}) where {T} = Base.OneTo(1)  # we only need to specialize this one
+@inline Base.axes(A::OffsetArray, d) = d <= ndims(A) ? IdOffsetRange(axes(parent(A), d), A.offsets[d]) : IdOffsetRange(Base.OneTo(1))
```
Comment (timholy) [inline src/OffsetArrays.jl:95]: Maybe this should be `IdOffsetRange(axes(parent(A), d)`? That way, whatever axis type the parent uses will be wrapped in the IdOffsetRange.
