### PR TITLE
Fix overflow for empty ranges

### LINKED ISSUE #225: Integer overflow in IdOffsetRange
```julia
julia> r = OffsetArrays.IdOffsetRange(1:0, typemax(Int))
IdOffsetRange(values=-9223372036854775808:9223372036854775807, indices=-9223372036854775808:9223372036854775807)
```

so for example

```julia
julia> OffsetVector(1:0, typemax(Int))
1:0 with indices -9223372036854775808:9223372036854775807
```

### PR DESCRIPTION
**Pull request by jishnub**
Fixes #225 partially (overflow is not allowed in the `OffsetArray` constructor for now).

Now 
```julia
julia> OffsetArray(1:0, typemax(Int))
ERROR: OverflowError: offset should be <= 9223372036854775806 corresponding to the axis Base.OneTo(0), received an offset 9223372036854775807
```

### CODE REVIEW

File: src/OffsetArrays.jl [hunk 1]
```diff
@@ -170,10 +174,15 @@ end
...
-    @eval @inline function $FT(A::OffsetArray, offsets::Tuple{Vararg{Integer}})
+    # empty tuples are handled here
+    @eval @inline function $FT(A::OffsetArray, offsets::Tuple{Vararg{Int}})
         _checkindices(A, offsets, "offsets")
+        foreach(overflow_check, axes(A), offsets)
         $FT(parent(A), map(+, A.offsets, offsets))
     end
+    @eval @inline function $FT(A::OffsetArray, offsets::Tuple{Integer,Vararg{Integer}})
+        $FT(A, map(x -> convert(Int, x)::Int, offsets))
+    end
```
Comment (johnnychen94) [inline src/OffsetArrays.jl:185]: I don't think this change is needed. `overflow_check` will eventually be called during the inner constructor, no?
At least by reverting the changes here I don't see any test failures.

Comment (jishnub) [reply src/OffsetArrays.jl:185]: Yes this is not strictly necessary as the inner constructor will catch it anyway, but this results in better error messages as the `+` in the `map` doesn't overflow either.

WIthout it:
```julia
julia> A = OffsetVector(0:-1, typemin(Int))
0:-1 with indices -9223372036854775807:-9223372036854775808

julia> OffsetVector(A, -1)
ERROR: OverflowError: offset should be <= 9223372036854775806 corresponding to the axis Base.OneTo(0), received an offset 9223372036854775807
```

With it
```julia

julia> OffsetVector(A, -1)
ERROR: OverflowError: offset should be >= 0 corresponding to the axis IdOffsetRange(values=-9223372036854775807:-9223372036854775808, indices=-9223372036854775807:-9223372036854775808), received an offset -1
```

Comment (johnnychen94) [reply src/OffsetArrays.jl:185]: This doesn't sound the right place to "fix" this error message to me and would be a little bit unintuitive from a maintenance perspective.

I think we can still achieve the same goal inside the overflow_check function. Or perhaps adding a comment for this explaining why we want to call overflow_check twice here. I prefer to only modify the overflow_check function.

Comment (jishnub) [reply src/OffsetArrays.jl:185]: The overflow happens here though, in the `map`. I'm not sure how to fix it in the inner constructor once the offset information is lost. How do you suggest addressing this?

Comment (johnnychen94) [reply src/OffsetArrays.jl:185]: Oh right. Sorry that I didn't notice this overflow in `offset`.

**Review by johnnychen94 — APPROVED** [review]
Thank you @jishnub for your consistent improvement to this package, you really are bug hunters!

File: src/OffsetArrays.jl (hunk 1 above)
Comment (jishnub) [reply src/OffsetArrays.jl]: I've updated the code now to make it more clear that the check here is to ensure that the offsets don't overflow when added. It's also a simpler check if only Integers are compared
