### PR TITLE
Reshape with an offset parent array

### LINKED ISSUE #219: Reshape is broken if the parent array does not use 1-based indexing
Currently many of the `reshape` methods defined in `OffsetArrays`  forward the parent, which may not work if the parent does not use 1-based indexing and does not define its own `reshape` methods. Reshaping may at times work correctly if `OffsetArrays` does not define these methods, so in a way `OffsetArrays` is currently breaking `reshape`, albeit for an `OffsetArray`.

Here is an example:

Define a type that does not use 1-based indexing
```julia
struct ZeroBasedRange{T,A<:AbstractRange{T}} <: AbstractRange{T}
    a :: A
    function ZeroBasedRange(a::AbstractRange{T}) where {T}
        @assert !Base.has_offset_axes(a)
        new{T, typeof(a)}(a)
    end
end

Base.parent(A::ZeroBasedRange) = A.a
Base.first(A::ZeroBasedRange) = first(A.a)
Base.length(A::ZeroBasedRange) = length(A.a)
Base.last(A::ZeroBasedRange) = last(A.a)
Base.size(A::ZeroBasedRange) = size(A.a)
Base.axes(A::ZeroBasedRange) = map(x -> Base.IdentityUnitRange(0:x-1), size(A.a))
Base.getindex(A::ZeroBasedRange, i::Int) = A.a[i + 1]
Base.step(A::ZeroBasedRange) = step(A.a)
function Base.show(io::IO, A::ZeroBasedRange)
    show(io, A.a)
    print(io, " with indices $(axes(A,1))")
end
```
Construct an `OffsetArray` wrapper:

```julia
julia> r = OffsetArray(ZeroBasedRange(3:4), 1);

julia> UnitRange(axes(r,1)) # r has 1-based indices
1:2

julia> reshape(r, (2,))
ERROR: ArgumentError: offset arrays are not supported but got an array with index other than 1
Stacktrace:
 [1] require_one_based_indexing at ./abstractarray.jl:89 [inlined]
 [2] _reshape at ./reshapedarray.jl:168 [inlined]
 [3] reshape at ./reshapedarray.jl:112 [inlined]
 [4] reshape(::OffsetArray{Int64,1,ZeroBasedRange{Int64,UnitRange{Int64}}}, ::Tuple{Int64}) at /home/jishnu/Dropbox/JuliaPackages/OffsetArrays.jl/src/OffsetArrays.jl:266
 [5] top-level scope at REPL[21]:1
```

If the forwarding methods defined in `OffsetArrays` are commented out:

```julia
julia> reshape(r, (2,)) # falls back to the Base method, and is a no-op if the lengths match
3:4 with indices Base.IdentityUnitRange(0:1) with indices 1:2
```

I'm not sure what's the best approach to fix this is. We may of course introduce more methods in `OffsetArrays` to deal with such specific cases, but that's playing whack-a-mole.

### PR DESCRIPTION
**Pull request by jishnub**
Fixes #219 

Now
```julia
julia> r = OffsetArray(IdentityUnitRange(0:1), -1)
Base.IdentityUnitRange(0:1) with indices -1:0

julia> reshape(r, 2) # Int arguments strip offsets
0:1

julia> reshape(r, (2,))
0:1

julia> reshape(r, :) # Colon preserves offsets for an OffsetVector
Base.IdentityUnitRange(0:1) with indices -1:0

julia> reshape(r, (:,))
Base.IdentityUnitRange(0:1) with indices -1:0
```

The last one is a bugfix, as on master

```julia
julia> reshape(r, :)
Base.IdentityUnitRange(0:1) with indices -1:0

julia> reshape(r, (:,))
ERROR: ArgumentError: offset arrays are not supported but got an array with index other than 1
Stacktrace:
```

### CODE REVIEW

**Comment by johnnychen94** [comment]
```julia
julia> reshape(r, :) # Colon preserves offsets for an OffsetVector
Base.IdentityUnitRange(0:1) with indices -1:0
```

On whether Colon should preserve the offset, looks like there's a back&forth here. https://github.com/JuliaArrays/OffsetArrays.jl/pull/228#issuecomment-817302031

**Comment by jishnub** [comment]
This is actually the present behavior (a single colon preserves offsets for an `OffsetVector`), and this PR doesn't change that.

The present behavior (on master) is:

```julia
julia> r = ones(2:3);

julia> reshape(r, :) # A single colon preserves offsets for an OffsetVector
2-element OffsetArray(::Vector{Float64}, 2:3) with eltype Float64 with indices 2:3:
 1.0
 1.0

julia> reshape(ones(2:3, 2:3), :) # offsets are stripped for an OffsetArray other than an OffsetVector
4-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0

julia> reshape(r, (2, :)) # colon with any other argument strips offsets
2×1 Matrix{Float64}:
 1.0
 1.0

julia> reshape(ones(2:3, 2:3), (3:4, :))
2×2 OffsetArray(::Matrix{Float64}, 3:4, 1:2) with eltype Float64 with indices 3:4×1:2:
 1.0  1.0
 1.0  1.0
```

In that regard I think #228 is the right step, where a `Colon` preserves offsets if possible. This PR preserves the present behavior and is not breaking.

File: src/OffsetArrays.jl [hunk 1]
```diff
@@ -347,15 +347,24 @@ end
 
 # Reshaping OffsetArrays can "pop" the original OffsetArray wrapper and return
 # an OffsetArray(reshape(...)) instead of an OffsetArray(reshape(OffsetArray(...)))
+# try to pass on the indices as received to the parent.
+# If the parent doesn't define an appropriate method, this will fall back to using the lengths
+# Short-circuit the case with matching indices to circumvent the Base restriction to 1-based indices
+_reshape(A::AbstractArray{<:Any,N}, ::NTuple{N,Union{Integer, AbstractUnitRange}}) where {N} = A
+_reshape(A::AbstractArray{<:Any,N}, inds::NTuple{N,OffsetAxis}) where {N} = (_colon_check(inds); A)
```
Comment (johnnychen94) [inline src/OffsetArrays.jl:354]: It seems that this method incorrectly captures many cases that should have been passed to `reshape(A, inds)` (the next line).

```julia
julia> A = OffsetArray(rand(4, 4), -1, -1);

julia> reshape(A, (2, :))
4×4 Matrix{Float64}:
 0.574079  0.87951   0.0342276  0.399441
 0.573279  0.978486  0.810298   0.245663
 0.649249  0.706191  0.600487   0.541148
 0.173837  0.132271  0.380885   0.953109
```

File: src/OffsetArrays.jl [hunk 2]
```diff
@@ -347,15 +347,24 @@ end
...
+_reshape(A, inds) = reshape(A, inds)
+_reshape_nov(A, inds) = no_offset_view(_reshape(A, inds))
```
Comment (johnnychen94) [inline src/OffsetArrays.jl:356]: It is subtle and can be fragile to require the caller to call `_reshape_nov(parent(A), inds)`.

I believe this one is equivalent?

```suggestion
_reshape_nov(A, inds) = _reshape(no_offset_view(A), inds)
```

File: src/OffsetArrays.jl (hunk 1 above)
Comment (johnnychen94) [reply src/OffsetArrays.jl:354]: Definitely no to me. In this case `:` should behave as a length placeholder. In master it is:

```julia
julia> reshape(A, (2, :)) |> axes
(Base.OneTo(2), Base.OneTo(8))
```

---

`:` preserve axes only when 1) the corresponding dimensional size matches and 2) all `inds` are range types:

```julia
A = OffsetArray(rand(4, 4), -1, -1);
reshape(A, (1:4, :)) # should be axes (1:4, 0:3)
reshape(A, (4, :)) # should be axes (1:4, 1:4)
```

For all other cases, I can't think of an unambiguous way to keep the offset information. Thus all other cases should be treated as length placeholder.

#228 corrects `reshape(A, (1:4, :))` but it's too breaking a change.

Comment (jishnub) [reply src/OffsetArrays.jl:354]: Aha sorry I had missed the length. This is clearly wrong

Comment (johnnychen94) [reply src/OffsetArrays.jl:354]: > 1) the corresponding dimensional size matches

I'm not very sure of it though. Because a reasonable way is to make axes `reshape(A, (0:1, :))` to `(0:1, 0:7)` since it faithfully keeps the offset `-1`.

File: src/OffsetArrays.jl (hunk 2 above)
Comment (jishnub) [reply src/OffsetArrays.jl]: This seems to be equivalent, so I've changed it to this now

File: src/OffsetArrays.jl (hunk 1 above)
Comment (jishnub) [reply src/OffsetArrays.jl]: Thanks for pointing this bug out, I've fixed this now

File: src/OffsetArrays.jl [hunk 3]
```diff
@@ -347,15 +347,23 @@ end
 
 # Reshaping OffsetArrays can "pop" the original OffsetArray wrapper and return
 # an OffsetArray(reshape(...)) instead of an OffsetArray(reshape(OffsetArray(...)))
+# try to pass on the indices as received to the parent.
+# If the parent doesn't define an appropriate method, this will fall back to using the lengths
+# Short-circuit the case with matching indices to circumvent the Base restriction to 1-based indices
```
Comment (johnnychen94) [inline src/OffsetArrays.jl:352]: Is this comment still useful? I guess no?

**Review by johnnychen94 — APPROVED** [review]
The last round of review with only some style suggestions. Feel free to merge when you're ready.

**Comment by jishnub** [comment]
@johnnychen94 I've added some bugfixes, although the fix seems a bit hacky. Could you take a look? The main changes are in https://github.com/JuliaArrays/OffsetArrays.jl/pull/245/commits/9f917603036455e3f133c3d94e42960c24b768e1, where I add `_reshape2` to deal with cases where `no_offset_view` applied to an `OffsetArray` returns another `OffsetArray`, which leads to stackoverflows. Now sure what's the best thing to do here, currently I just push the reshape to the parent and hope for the best.

**Review by johnnychen94 — APPROVED** [review]
I can basically get your points here. And yes it is also tricky for me.

There might be some deeply hidden bugs but nothing suspicious to me so far.
