### PR TITLE
Correct bounds checking for AbstractVectors with no indices specified (fixes #194)

### LINKED ISSUE #194: OffsetArray accesses out-of-bounds memory and returns an incorrect value when indexing with []
It is possible that this happens due to an incorrect use of `@inbounds`:

```julia
julia> using OffsetArrays

julia> OffsetArray([0], 1)[]
4562921808

julia> [OffsetArray([0], 1)[] for _ in 1:10]
10-element Array{Int64,1}:
           0
  4396158144
  4582191936
  4582191936
  4396158144
           0
  4396158144
  8589934592
 12884901888
           0

julia> OffsetArray([0], 100:100)[]
4614560496
```

```
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by jishnub**
After this PR

```julia
julia> OffsetArray([0], 1)[]
ERROR: BoundsError: attempt to access 1-element OffsetArray(::Array{Int64,1}, 2:2) with eltype Int64 with indices 2:2 at index []

julia> OffsetArray([6], 1:1)[]
6
```

### CODE REVIEW

**Comment by yurivish** [comment]
Thank you for the quick fix!

Is it odd that coverage is reporting that the added `Base.checkbounds_indices` indices method is reported as not being covered by tests, even though the tests you've added presumably hit that method (otherwise they would not pass)?

**Comment by jishnub** [comment]
It's perhaps some inlining quirk. I've added an explicit test, hopefully coverage will be happy now.

File: src/axes.jl [hunk 1]
```diff
@@ -179,6 +179,14 @@ Base.show(io::IO, r::IdOffsetRange) = print(io, "OffsetArrays.IdOffsetRange(",fi
 # Optimizations
 @inline Base.checkindex(::Type{Bool}, inds::IdOffsetRange, i::Real) = Base.checkindex(Bool, inds.parent, i - inds.offset)
 
+# issue 194
+# The indexing operation A[] gets mapped to A[1]. 
+# the bounds-checking for this needs to be handled separately for AbstractVectors
```
Comment (johnnychen94) [inline src/axes.jl:184]: Might also worth a reference to https://github.com/JuliaLang/julia/issues/39379 so that if Base gets updated, we can then add a version check here.

**Review by johnnychen94 — APPROVED** [review]
Nice detective work. No objection in merging this.

**Comment by mbauman** [comment]
The problem here isn't the bounds check.  Indeed, the expression `OffsetArray([6], 2:2)[]` _should_ work and return a 6.  Where we are hardcoding a `1` is in the linear indexing transform:

```Julia
julia> Base._to_linear_index(OffsetArray([6], 2:2))
1
```

This is where the problem is:

https://github.com/JuliaLang/julia/blob/69d24532980bda6db510b6d4b71f66e7ffff2e81/base/abstractarray.jl#L1196
