### PR TITLE
Convert to OffsetArrays

### LINKED ISSUE #171: missing convert method
```julia
convert(Vector, 1:5)
convert(OffsetVector, 1:5) # doesn't work
```

Will it be type piracy if we define `convert(::Type{T}, x) where {T<:OffsetArray}`?

### PR DESCRIPTION
**Pull request by jishnub**
Fixes #171 ~partly~

Now conversion works if the `OffsetArray` type is fully specified (~doesn't work at present if it's left as a `UnionAll`~ works now).

```julia
julia> d = Diagonal([1,1,1])
3×3 Diagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅
 ⋅  1  ⋅
 ⋅  ⋅  1

julia> convert(OffsetMatrix{Float64, Matrix{Float64}}, d)
3×3 OffsetArray(::Matrix{Float64}, 1:3, 1:3) with eltype Float64 with indices 1:3×1:3:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

julia> convert(OffsetMatrix{Float32, Matrix{Float32}}, d)
3×3 OffsetArray(::Matrix{Float32}, 1:3, 1:3) with eltype Float32 with indices 1:3×1:3:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

julia> convert(OffsetMatrix{Float32, Matrix{Float32}}, OffsetArray(d, 2, 2))
3×3 OffsetArray(::Matrix{Float32}, 3:5, 3:5) with eltype Float32 with indices 3:5×3:5:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0
```

As a consequence this matrix vector product works now (used to error earlier):

```julia
julia> a = [MMatrix{2,2}(1:4) for i = 1:2];

julia> oa = [OffsetArray(ai, 0, 0) for ai in a];

julia> b = ones(2,2);

julia> b * oa
2-element Vector{OffsetMatrix{Float64, SizedMatrix{2, 2, Float64, 2, Matrix{Float64}}}}:
 [2.0 6.0; 4.0 8.0]
 [2.0 6.0; 4.0 8.0]
```

These constructors create copies if necessary.

~I have not added the other `UnionAll` constructors deliberately as it'll not be clear if the `OffsetArray(::AbstractArray)` constructor creates a copy or not. Currently it doesn't create a copy for `OffsetArray(::Array{T,0})`, so creating a copy for other arrays might be confusing. On the other hand, we may choose to not create a copy at all, which will make the `OffsetArray` constructor behave differently from `Array`~.

### CODE REVIEW

File: src/OffsetArrays.jl [hunk 1]
```diff
@@ -223,6 +223,11 @@ for FT in (:OffsetArray, :OffsetVector, :OffsetMatrix)
     @eval @inline $FT(A::AbstractArray, origin::Origin) = $FT(A, origin(A))
 end
 
+# conversion-related methods
+OffsetArray{T,N,A}(M::AbstractArray) where {T,N,A<:AbstractArray{T,N}} = OffsetArray{T,N,A}(A(M), ntuple(zero, Val(N)))
+OffsetArray{T,N,A}(M::OffsetArray{<:Any,N}) where {T,N,A<:AbstractArray{T,N}} = OffsetArray{T,N,A}(A(parent(M)), M.offsets)
+Base.convert(::Type{T}, M::AbstractArray) where {T<:OffsetArray} = M isa T ? M : T(M)
```
Comment (johnnychen94) [inline src/OffsetArrays.jl:229]: We can perhaps add non-parametric versions of it?

```julia
for FT in (:OffsetArray, :OffsetVector, :OffsetMatrix)
    @eval Base.convert(::Type{$FT}, M::AbstractArray) = M isa $FT ? M : $FT(M, map(_indexoffset, axes(M)))
end
```

this makes

```julia
julia> convert(OffsetVector, 1:5)
1:5 with indices 1:5
```

**Review by johnnychen94 — COMMENTED** [review]
> it'll not be clear if the OffsetArray(::AbstractArray) constructor creates a copy or not

We won't do deepcopy; most constructors don't do it. Since `offsets` is a tuple, copy the wrapper type or not doesn't make much difference.

File: src/OffsetArrays.jl (hunk 1 above)
Comment (jishnub) [reply src/OffsetArrays.jl:229]: We may add the relevant constructors instead of adding more `convert` methods, as this might reduce invalidations

**Comment by jishnub** [comment]
I've added the extra constructors necessary, so now general conversions work.

```julia
julia> convert(OffsetVector, 1:4)
1:4 with indices 1:4

julia> convert(OffsetVector{Float32}, 1:4)
1.0f0:1.0f0:4.0f0 with indices 1:4
```

File: src/utils.jl [hunk 2]
```diff
@@ -82,3 +82,6 @@ _maybewrapoffset(r::AbstractUnitRange, of, ::Base.OneTo) = no_offset_view(r)
 _maybewrapoffset(r::AbstractVector, of, ::Base.OneTo) = no_offset_view(r)
 _maybewrapoffset(r::AbstractUnitRange, of, ::Any) = IdOffsetRange(UnitRange(r), of)
 _maybewrapoffset(r::AbstractVector, of, axs) = OffsetArray(r .+ of, axs)
+
+_maybemap(::Type{T}, M::AbstractArray{T}) where {T} = M
+_maybemap(T, M::AbstractArray) = map(T, M)
```
Comment (johnnychen94) [inline src/utils.jl:87]: Mimic `MappedArrays.of_eltype`:

```suggestion
_of_eltype(::Type{T}, M::AbstractArray{T}) where {T} = M
_of_eltype(T, M::AbstractArray) = map(T, M)
```

File: src/OffsetArrays.jl [hunk 3]
```diff
@@ -219,10 +222,27 @@ for FT in (:OffsetArray, :OffsetVector, :OffsetMatrix)
     end
 
     @eval @inline $FT(A::AbstractArray, inds::Vararg) = $FT(A, inds)
+    @eval @inline $FT(A::AbstractArray) = $FT(A, ntuple(zero, Val(ndims(A))))
 
     @eval @inline $FT(A::AbstractArray, origin::Origin) = $FT(A, origin(A))
 end
 
+# conversion-related methods
+OffsetArray{T}(M::AbstractArray, I::Vararg) where {T} = OffsetArray{T}(M, I)
```
Comment (johnnychen94) [inline src/OffsetArrays.jl:231]: We still need to explicitly fix the `Vararg` here (and same for the other two):

```suggestion
OffsetArray{T1}(M::AbstractArray{T2, N}, I::Vararg{OffsetAxisKnownLength, N}) where {T1, T2, N} = OffsetArray{T1}(M, I)
```

Otherwise, unintentional incorrect inputs would trigger a StackOverflow:

```julia
A = rand(4, 4)

# StackOverflow
convert(OffsetArray{Float64, 1}, A)
convert(OffsetArray{Float64, 3}, A)
```

**Review by johnnychen94 — APPROVED** [review]
Except for the small "bug", all others are good to me. (I like how you write tests 👍 )

**Review by johnnychen94 — APPROVED** [review]
